apache/httpcomponents-core

httpcore5/src/main/java/org/apache/hc/core5/http/HttpStatus.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/EnglishReasonPhraseCatalog.java
=> HTTPCORE-552: add http status code 103

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java
It is possible, in principle, for the ReactiveDataConsumer's update channel to be null when a flush occurs. If this happens, the window update increment will be dropped, permanently decreasing the size of the transfer window. With this change, window update increments will accumulate across flushes until the update channel is set.
=> Don't drop ReactiveDataConsumer window updates

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/H2ServerBootstrap.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/framework/TestingFramework.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/Http1AuthenticationTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/Http1ServerAndRequesterTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/Http2ServerAndRequesterTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/AsyncServerBootstrap.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/ServerBootstrap.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/bootstrap/TestAsyncServerBootstrapLookupRegistry.java
=> HTTPCORE-570

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/reactive/ReactiveClientTest.java
This fixes a race condition in ReactiveDataConsumer that would cause the
input window to never be updated over HTTP/1.x connections. The bug
occurs when consume is the first method to call flushToSubscriber,
enough data has been received to exhaust the initial input window in the
stream duplexer, and there are still downstream requests for data that
haven't been served.
ReactiveDataConsumer attempts to flush data downstream whenever it gets
a chance, and only one thread is allowed to flush. After flushing, it
signals the number of bytes flushed to its capacity channel.
If the flush occurs because AbstractHttp1StreamDuplexer is calling
consume, it guarantees the capacity channel won't be set until consume
(and the flush) returns.  When there are still outstanding requests
(meaning the …
=> HTTPCORE-568: Signal capacity in ReactiveDataConsumer whenever possible

RELEASE_NOTES.txt, httpcore5-reactive/pom.xml, httpcore5-testing/pom.xml, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/SerializableEntity.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/package-info.java, pom.xml
If I hear no complaints I will proceed with HttpCore 5.0-beta7 release.
=> Release preparation

RELEASE_NOTES.txt, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreListeningIOReactor.java
Provide more information when a BindException occurs.
=> Provide more information when a BindException occurs.

httpcore5/src/main/java/org/apache/hc/core5/util/Timeout.java
Very small change, but it was bothering me.
=> Fix Timeout#ofMillis javadoc reference

httpcore5/src/main/java/org/apache/hc/core5/reactor/ssl/SSLIOSession.java
It is possible for SSLIOSession#setSocketTimeout to be called between
SSLIOSession#new and SSLIOSession#initialize, which will cause the
connection timeout to be overwritten. This change defers the connection
timeout configuration until the #initialize method is called.
=> SSLIOSession: Improve connectTimeout implementation

httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncFileServerExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicFileServerExample.java
Better messages in file server examples.
=> Better messages in file server examples.

pom.xml
Update RxJava from 2.2.7 to 2.2.8.
=> Update RxJava from 2.2.7 to 2.2.8.

httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/HttpRequester.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreIOReactor.java
In order to allow users to run under a security manager that only grants
connect permission to the httpcore codebase the connect methods should
be executed in a doPriveledged block.
This is certainly not the only issue that users run into when they
install a SecurityManager with strict permissions but certainly the
most prominent and most likely one. Upstream components like the client
might also need to protect places accessing the proxy selector etc.
=> Execute Socket[Channel]#connect under doPrivileged

httpcore5/src/main/java/org/apache/hc/core5/pool/LaxConnPool.java
=> HTTPCORE-589 Fix LaxConnPool to ensure pending requests assigned connections

httpcore5/src/main/java/org/apache/hc/core5/pool/LaxConnPool.java
by testing that lease Future completion is successful.
=> HTTPCORE-590 Ensure LaxConnPool doesn't leak connections

httpcore5/src/main/java/org/apache/hc/core5/http/message/StatusLine.java
***NOTE***: The added code is taken almost verbatim from https://github.com/jax-rs/api/blob/master/jaxrs-api/src/main/java/javax/ws/rs/core/Response.java.
---
It is common in apps that use HTTP clients to check if a response status code is 2xx, 3xx, 4xx, 5xx, etc. and conditionally execute code based on that.
Spring's [HttpStatus](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html) for example, provides these methods:
```
public boolean is1xxInformational()
public boolean is2xxSuccessful()
public boolean is3xxRedirection()
public boolean is4xxClientError()
public boolean is5xxServerError()
```
as well as
```
public HttpStatus.Series series()
```
which returns an instance of [HttpStatus.Series](https://docs.spring.io/spring-framework/do …
=> Added family property

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/nio/pool/H2ConnPool.java, httpcore5-testing/src/main/java/org/apache/hc/core5/benchmark/HttpBenchmark.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/SocksProxy.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/classic/ClassicTestClient.java, httpcore5/src/main/java/org/apache/hc/core5/concurrent/BasicFuture.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/HttpRequester.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/RequestListener.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/BHttpConnectionBase.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/SocketConfig.java, httpcore5/src/main/java/org/apache/hc/core5/pool/LaxConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/pool/StrictConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/AbstractIOSessionPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/AbstractSingleCoreIOReactor.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/IOReactorConfig.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/InternalChannel.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/MultiCoreIOReactor.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreIOReactor.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreListeningIOReactor.java, httpcore5/src/main/java/org/apache/hc/core5/util/Deadline.java, httpcore5/src/main/java/org/apache/hc/core5/util/TimeValue.java, httpcore5/src/main/java/org/apache/hc/core5/util/TimeoutValueException.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/TestSSLContextBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestDeadline.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestDeadlineTimeoutException.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTimeValue.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTimeout.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTimeoutValueException.java
HTTPCORE-611
Minor glitches with TimeValue
https://issues.apache.org/jira/browse/HTTPCORE-611
=> [HTTPCORE-611] Minor glitches with TimeValue.

httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/AbstractHttp1StreamDuplexer.java
It's not the best idea to synchronize on an object we give users access to.
=> AbstractHttp1StreamDuplexer: don't synchronize on `this`

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java
It is possible for two threads to race in such a way that a call to a
method like `ReactiveDataConsumer#streamEnd` will never result in a call
to `Subscriber#onComplete` from either thread. These races are solved by
synchronizing the `flushToSubscriber` method, which is currently only
protected against reentrant calls from the same thread.
=> ReactiveDataConsumer: Synchronize `flushToSubscriber`

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java, httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveResponseConsumer.java
@rschmitt Would you be willing to consider this change-set intended to simplify resource de-allocation logic in the reactive data consumer code?
=> Simplified resource deallocation by reactive data consumer

httpcore5/src/main/java/org/apache/hc/core5/http/HttpStatus.java
https://issues.apache.org/jira/browse/HTTPCORE-618
=> Httpcore 618 http status as a class

httpcore5/src/main/java/org/apache/hc/core5/reactor/EventMask.java
https://issues.apache.org/jira/browse/HTTPCORE-619
=> Httpcore 619 event mask as a class

httpcore5-testing/src/main/java/org/apache/hc/core5/benchmark/HttpBenchmark.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/LoggingIOSession.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSession.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSessionImpl.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/InternalDataChannel.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/ssl/SSLIOSession.java
[HTTPCORE-620] Refactor int constants from org.apache.hc.core5.reactor.IOSession into an enum.
https://issues.apache.org/jira/browse/HTTPCORE-620
=> [HTTPCORE-620] Refactor int constants from org.apache.hc.core5.reactor.IOSession into an enum

httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/BHttpConnectionBase.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/HttpRequestExecutor.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/BHttpConnection.java, httpcore5/src/main/java/org/apache/hc/core5/util/Args.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestBHttpConnectionBase.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestHttpRequestExecutor.java
https://issues.apache.org/jira/browse/HTTPCORE-623
=> [HTTPCORE-623] BHttpConnection#isDataAvailable int -> Timeout

httpcore5/src/main/java/org/apache/hc/core5/http/Method.java
=> Add org.apache.hc.core5.http.Method.normalizedValueOf(String) for use by

httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EntityUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestEntityUtils.java
https://issues.apache.org/jira/browse/HTTPCLIENT-2098
=> Read specified number of bytes from HttpEntity

httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/H2GreetingServer.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/SocksProxy.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/support/TerminalServerFilter.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/TokenParser.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/entity/NoopEntityConsumer.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/BasicClientExchangeHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/ImmediateResponseExchangeHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/HttpContext.java, httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/pool/LaxConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/EndpointParameters.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSession.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreIOReactor.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SocksProxyProtocolHandler.java, httpcore5/src/main/java/org/apache/hc/core5/ssl/SSLContextBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/nio/CodecTestUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/nio/TestIdentityDecoder.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/nio/TestLengthDelimitedDecoder.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/TestMessageSupport.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/TestSSLContextBuilder.java
Each commit in this PR comprise one kind of cleanup/change:
- Use try-with-resources.
- Use diamonds.
- Add missing @override.
- Make better use of Map APIs.
- Remove redundant modifiers. …
- Use Collections.addAll() API instead of loops.
- Remote extra semicolons (;).
=> Master try w res and more

httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ChunkedInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ChunkedOutputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ContentLengthInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ContentLengthOutputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/IdentityInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/IdentityOutputStream.java
See also [HTTPCORE-655](https://issues.apache.org/jira/browse/HTTPCORE-655)
=> Improve HTTP input and output streams' documentation regarding close()

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/frame/FrameFlag.java, httpcore5-testing/src/main/java/org/apache/hc/core5/benchmark/ResultFormatter.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/SocksProxy.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/framework/ClassicTestClientAdapter.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/ReactiveTestUtils.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/classic/ClassicIntegrationTest.java, httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/NameValuePairListMatcher.java, httpcore5/src/test/java/org/apache/hc/core5/http/TestContentType.java, httpcore5/src/test/java/org/apache/hc/core5/http/TestHttpExceptions.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicReverseProxyExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestChunkCoding.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestDefaultBHttpServerConnection.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestSessionInOutBuffers.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TimeoutByteArrayInputStream.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/nio/TestSessionInOutBuffers.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestByteArrayBuffer.java
* Add final to variable
* Use 'StringBuilder' instead 'StringBuffer'
* Concatenate with append instead
* Use Standard Charset object
=> Minor Improvement:

httpcore5-h2/pom.xml, httpcore5-reactive/pom.xml, httpcore5-testing/pom.xml, httpcore5/pom.xml, pom.xml, src/site/resources/css/site.css, src/site/site.xml
see https://github.com/apache/httpcomponents-client/pull/280 (and previous commits already merged)
=> updates equivalent to httpcomponents-client

httpcore5/src/main/java/org/apache/hc/core5/http/protocol/UriPatternType.java, httpcore5/src/main/java/org/apache/hc/core5/util/LangUtils.java
* Simplify Case
* Simplify Object equals
=> Minor Improvements:

httpcore5-reactive/pom.xml
Edited via the github editor. The change on the last character of the file is unintentional.
=> upgrade org.reactivestreams:reactive-streams to version 1.0.3

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java
Add new content type --> application/problem+json
https://tools.ietf.org/html/rfc7807#section-6.1
=> HTTPCORE-667 - Add new Content Type application/problem+json

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java
Add new content type --> text/event-stream
Events W3C recommendation
https://www.w3.org/TR/eventsource/
=> HTTPCORE-668 - W3C recommendation text/event-stream

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java
* Add new content types:
- application/x-ndjson
- application/pdf
- application/problem+xml
- application/rss+xml
- multipart/mixed
- multipart/related
- text/markdown
* Add charset constant
=> Add new content types

httpcore5/src/main/java/org/apache/hc/core5/http/HttpHeaders.java
Add new header
Set-Cookie --> https://tools.ietf.org/html/rfc2109#section-4.2.2
Link --> href="https://tools.ietf.org/html/rfc5988
Cookie --> https://tools.ietf.org/html/rfc2109
Content-Disposition --> https://tools.ietf.org/html/rfc6266
Access-Control-Request-Method --> https://www.w3.org/TR/cors
Access-Control-Request-Headers  --> https://www.w3.org/TR/cors
Access-Control-Max-Age --> https://www.w3.org/TR/cors
Access-Control-Expose-Headers --> https://www.w3.org/TR/cors
Access-Control-Allow-Origin --> https://www.w3.org/TR/cors
Access-Control-Allow-Methods --> https://www.w3.org/TR/cors
Access-Control-Allow-Credentials -->https://www.w3.org/TR/cors
=> HTTPCORE-670 -  Add new headers

httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java
Improve the text utils method by checking the length of the string to check,
=> improve Text Utils methods

httpcore5-testing/src/main/java/org/apache/hc/core5/testing/SocksProxy.java, httpcore5/src/main/java/org/apache/hc/core5/net/InetAddressUtils.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SocksProxyProtocolHandler.java, httpcore5/src/main/java/org/apache/hc/core5/util/Args.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestArgs.java
* Re use IPV4 and IPV6 constant
* Improve and clean validation class
* new method to check if an object `isEmpty `
* Add missing test
=> Improve and clean validation class

httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSessionListener.java
=> Fix typo in IOSessionListener

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/nio/pool/H2ConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSessionImpl.java
@rschmitt Please review or test locally if possible.
=> HTTPCORE-672: H2ConnPool incorrectly handles validation of closed sessions

httpcore5/src/main/java/org/apache/hc/core5/http/HttpHost.java, httpcore5/src/main/java/org/apache/hc/core5/net/Host.java, httpcore5/src/main/java/org/apache/hc/core5/net/URIAuthority.java, httpcore5/src/main/java/org/apache/hc/core5/net/URISupport.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestHost.java
=> Improved parsing and formatting of URI components

httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/BHttpConnectionBase.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/BHttpConnection.java
* Convert argument to const
* Correct javadoc for isStale()
=> * Convert argument to const

httpcore5/src/main/java/org/apache/hc/core5/pool/StrictConnPool.java
This is an alternative to the implementation proposed in #293 as
described by
https://github.com/apache/httpcomponents-core/pull/293#discussion_r654678265
=> Fix data race in StrictConnPool

httpcore5/src/main/java/org/apache/hc/core5/reactor/IOReactorConfig.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreIOReactor.java, httpcore5/src/test/java/org/apache/hc/core5/reactor/IOReactorConfigTest.java
Probably it's good idea make this change now that we are in a new Release.
=> Use cameCase in isSoKeepAlive method.

pom.xml
Bump log4j to 2.16.0 and align with httpcomponents-client.
=> Bump version log4j to 2.16.0

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/H2OnlyClientProtocolNegotiator.java
Aligned with the implementation of the latest release to get rid of
ProtocolNegotiationException:
https://github.com/apache/httpcomponents-core/blob/rel/v5.2-beta2/httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientH2PrefaceHandler.java#L142
cc @ok2c
=> HTTPCLIENT-2222: fixed ProtocolNegotiationException

httpcore5/src/test/java/org/apache/hc/core5/concurrent/TestBasicFuture.java
- Use AtomicBoolean for future completion tracking.
- Simplify async behavior and improve test determinism.
=> Refactor testGetWithTimeout for Reliability

httpcore-nio/src/main/java/org/apache/http/impl/nio/reactor/AbstractMultiworkerIOReactor.java
When creating IO Dispatchers, there is possibility that an exception(fatal) can occur due to which dispatchers/worker threads creation fail and requests in queue aren't processed forever. See for example: https://issues.apache.org/jira/browse/HTTPCORE-758 
With these changes, if there are any exceptions while creating IO dispatchers, shutdown() will be called and all the components down the line are shutdown and cancel() will be called for future callbacks references, thus the caller won't wait indefinitely for the response from Apache Http client.
=> Fix exception handling when creating IO Dispatchers

httpcore5/src/main/java/org/apache/hc/core5/net/PercentCodec.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestPercentCodec.java
@arturobernalg I moved some of your code from client to core. Please review.
=> Support for percent coding as defined in RFC 5987

httpcore5/src/main/java/org/apache/hc/core5/net/WWWFormCodec.java, httpcore5/src/main/java/org/apache/hc/core5/pool/LaxConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/util/Args.java, httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java
- Removed unused private fields and methods
- Minor optimizations in TextUtils
=> Optimizations

httpcore5/src/main/java/org/apache/hc/core5/net/Host.java, httpcore5/src/main/java/org/apache/hc/core5/net/InetAddressUtils.java, httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestInetAddressUtils.java
Update the method parameter of InetAddressUtils from String to CharSequence.
Sometimes I need to pass parts of a String(create a String slice) to this method instead of splitting the String into multiple pieces.
=> Update the method parameter from String to CharSequence.

httpcore5/src/main/java/org/apache/hc/core5/http/io/HttpClientConnection.java
Fix descriptions that seem inaccurate.
=> Fix HttpClientConnection.isConsistent description

httpcore5/src/main/java/org/apache/hc/core5/http/ProtocolVersion.java
Error message for Protocol Major Version was incorrect.
=> Update error message in ProtocolVersion

httpcore5/src/main/java/org/apache/hc/core5/function/IOFunction.java
@arturobernalg I would like to move your `IOFunction` to core proper. Please double-check.
=> IOFunction functional interface
