apache/httpcomponents-core

httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/DefaultBHttpClientConnection.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestDefaultBHttpClientConnection.java
As per spec these responses are terminated by the end of stream.
Issue: https://issues.apache.org/jira/browse/HTTPCORE-559
Note: this PR breaks one existing unit test - namely {{testReadResponseNoEntity}} from {{TestDefaultBHttpClientConnection}}.  The test is trivial to fix, but I'm not sure what you want the desired behaviour to be when an 'empty' response is returned.  Previously the result was a null entity, but with my change the result is now an empty entity, an entity with no content.  I think this is fine, but you may not.
=> Allow default http client connection to read simple streamed responses

httpcore/src/main/java/org/apache/http/config/SocketConfig.java
This reflects current actual behavior.
Context: Thread on hc-dev mailing list
Message-ID: <3379cf792422e6b1c9df42d78d40929c0ed2603f.camel@osimis.io>
Subject: Documented default value for TCP_NODELAY
Date: Thu, 17 Jan 2019 21:46:35 +0100
https://apache-hc-dev.markmail.org/message/37ldla5s6hvofztd
=> Document TCP_NODELAY default as "true"

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/Http2MultiplexingRequester.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/Http2MultiplexingRequesterBootstrap.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/nio/pool/H2ConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/AbstractIOSessionPool.java, httpcore5/src/test/java/org/apache/hc/core5/reactor/TestAbstractIOSessionPool.java
This change essentially reverts a portion of 40cae2275 that appears to
have been unnecessary. Since the `requestTimeout` parameter is always a
connection timeout (at least in the client-side code), we don't need to
dedicate an additional parameter to the TLS handshake timeout value: we
simply use the `requestTimeout` (which has been renamed `connectTimeout`
for clarity).
=> Merge connect and handshake timeouts in AbstractIOSessionPool

httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/AbstractHttp1StreamDuplexer.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/nio/TestAbstractHttp1StreamDuplexerCapacityWindow.java
This solves two issues:
1. A data consumer that retains a reference to an old capacity channel
will no longer be able to modify state for future requests occurring on
the same connection (e.g. updating the window or requesting reads).
2. Coupling changes to the input window with changes to the io session
state prevents a race condition occuring when a consumer asynchronously
calls CapacityChannel#udpate at the same moment the input window is
exhausted by new input. Without synchronization, it was possible (albeit
unlikely) for the IO thread to decrease the window below zero, a
consumer thread to request input by calling CapacityChannel#update, then
the IO thread to clear the read request.
=> Add a thread-safe capacity channel to AbstractHttp1StreamDuplexer

httpcore-nio/src/main/java/org/apache/http/impl/nio/codecs/IdentityDecoder.java, httpcore-nio/src/main/java/org/apache/http/impl/nio/codecs/LengthDelimitedDecoder.java, httpcore-nio/src/test/java/org/apache/http/impl/nio/codecs/TestIdentityDecoder.java, httpcore-nio/src/test/java/org/apache/http/impl/nio/codecs/TestLengthDelimitedDecoder.java
Limit the number of bytes read from the internal buffer when
transferring, so that the maximum requested ('count') is respected.
=> HTTPCORE-573 FileContentDecoder don't always enforce the maximum number of bytes to transfer

httpcore5/src/main/java/org/apache/hc/core5/http/ClassicHttpRequest.java, httpcore5/src/main/java/org/apache/hc/core5/http/HttpEntityContainer.java
Refactor **ClassicHttpRequest** and **ClassicHttpResponse** interfaces to extend a new interface called **HttpEntityContainer**. This permits for writing common entity code for both requests and responses without testing and casting for two cases.
=> Refactor ClassicHttpRequest and ClassicHttpResponse interfaces to extend

RELEASE_NOTES.txt, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientHttp2StreamHandler.java, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/examples/ReactiveFullDuplexServerExample.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/Http1IntegrationTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/reactive/ReactiveClientTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/HttpHeaders.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/HttpRequestExecutor.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ClientHttp1StreamHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/support/AbstractHttpServerAuthFilter.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/support/BasicHttpServerExpectationDecorator.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/support/HttpServerExpectationFilter.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/AbstractAsyncServerAuthFilter.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/AsyncServerExpectationFilter.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/BasicAsyncServerExpectationDecorator.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncReverseProxyExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicReverseProxyExample.java, pom.xml
Add KEEP_ALIVE constant and use existing header for PROXY_AUTHENTICATE.
=> Add KEEP_ALIVE constant and use existing header for PROXY_AUTHENTICATE.

httpcore5/src/main/java/org/apache/hc/core5/http/message/HeaderGroup.java
Make HeaderGroup.EMPTY static.
=> (HTTPCORE-578) Incorrect serialization of HeaderGroup

httpcore-nio/src/main/java/org/apache/http/impl/nio/reactor/DefaultConnectingIOReactor.java, httpcore/src/main/java/org/apache/http/impl/pool/BasicConnFactory.java
In order to allow users to run under a security manager that only grants
connect permission to the httpcore codebase the connect methods should
be executed in a doPriveledged block.
This is certainly not the only issue that users run into when they
install a SecurityManager with strict permissions but certainly the
most prominent and most likely one. Upstream components like the client
might also need to protect places accessing the proxy selector etc.
Backport of #135
=> Execute Socket[Channel]#connect under doPrivileged

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java
While using core 4.4 with `StringEntity(string,mimetype,charset)` constructor deprecated we can no longer specify `application/soap+xml` although some apis require this
- Add `application/soap+xml` as a content type
=> Add SOAP xml content type

httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2AlpnTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2ProtocolNegotiationTest.java, httpcore5/src/main/java/org/apache/hc/core5/util/ReflectionUtils.java
Prior to this change, attempts to reflectively invoke methods on
protected classes in other modules could fail on JDK9 and above.
Currently, the methods in ReflectionUtils are only used to get and set
properties related to ALPN on SSLEngine instances at runtime. On JDK11,
reflectively invoking the `getApplicationProtocol` method on
`SSLEngineImpl`, a protected class, throws an `IllegalAccessException`.
`callGetter` swallows this and returns `null`, causing the client
runtime to ignore whatever protocol was negotiated with ALPN and default
to HTTP/1.1.
This specific reflective access is still illegal and will eventually
break in a future Java release. A proper fix would require creating a
multi-release jar with a dedicated SSLEngine accessor class for JDK9+
that can natively invoke these …
=> Set accessiblity flag on reflected methods in ReflectionUtils

httpcore5/src/main/java/org/apache/hc/core5/util/TimeValue.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTimeValue.java
@garydgregory TimeValue is mostly your code. Could you please please take a look at this change-set and let me know if you find anything disagreeable?
=> Time values

httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/BasicResponseConsumer.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/BasicResponseProducer.java
Wrapped AsyncEntityConsumers and AsyncEntityProducers were not receiving failed()
calls before releaseResources() when an exchange was abnormally terminated.
Note that AsyncEntityProducer behavior is slightly different from AsyncEntityConsumer behavior in that consumers can receive no further calls from BasicResponseConsumer after releaseResources() is called because the consumer reference is atomically discarded, but producers can. I didn't want to change the member variable state without guidance.
=> Propagate BasicResponse{Consumer,Producer}#failed() to data{Consumer,Producer}

httpcore-nio/src/main/java/org/apache/http/impl/nio/reactor/SessionRequestImpl.java
Currently there are 2 states being maintained in SessionRequestImpl, terminated / completed.
Both of them are used differently, but one can be updated before the second is updated and read by the other's value. This may lead to race conditions which are prone to error.
One such example is issue https://issues.apache.org/jira/browse/HTTPASYNC-152.
=> [HTTPASYNC-152] Adds state in SessionRequestImpl to avoid race condition in changing multiple variables

httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EntityUtils.java, httpcore5/src/main/java/org/apache/hc/core5/util/Args.java
EntityUtils clean ups and internal refactoring. If this is OK, I'll do something similar for 4.5.x if needed.
=> EntityUtils clean ups and internal refactoring

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/nio/pool/H2ConnPool.java
Previously only positive values were used for checking the validity of a potentially stale connection, now 0 is allowed
=> HTTPCORE-613_2: Now allowing 0 for validaterAfterInactivity

httpcore5/src/main/java/org/apache/hc/core5/pool/StrictConnPool.java, httpcore5/src/test/java/org/apache/hc/core5/pool/TestStrictConnPool.java
I mentioned in the mailing list that a connection request does not fail immediately when the time to acquire the StrictConnPool lock is longer than the requestTimeout. Instead it will only fail when the lock is finally acquired and the deadline is checked in processPendingRequest(). @ok2c agreed and suggested I propose a PR.
This PR changes StrictConnPool.lease to use the requestTimeout when attempting to grab the lock. If the lock can't be acquired within the timeout the request is failed with a DeadlineTimeoutException.
A few comments:
1. tryLock(timeout) is interruptible whereas lock() is not. I'm unclear if this would break any existing behavior.
2. I don't love that acquisition of the lock is captured in a boolean, it feels slightly dangerous if this block gets more complex down the …
=> Allow for timeout while acquiring lock in StrictConnPool.

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java, httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveResponseConsumer.java
Presently the contract of `AsyncDataConsumer` and its implementations is
that `streamEnd` is only called at the end of a data stream. If the HTTP
message does not enclose an entity, then no such stream actually exists;
in this case, `releaseResources` is called instead. This change teaches
`ReactiveResponseConsumer` to call `Subscriber#onComplete` in this case.
=> ReactiveResponseConsumer: Fix empty response handling

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java
According to RFC7540 §6.9.2 ("Initial Flow-Control Window Size"), "the
connection flow-control window can only be changed using WINDOW_UPDATE
frames." Furthermore, according to §6.9 ("WINDOW_UPDATE"), the window
size increment must be an unsigned integer, with a legal range being "1
to 2^31-1 (2,147,483,647) octets." In other words, when the client uses
a SETTINGS frame to shrink the initial window size to a value smaller
than the default (65,535 bytes), the resulting delta must only be
applied to the existing child streams, and not the connection window
itself. (While a *positive* delta can be applied to the connection
window, this must be done explicitly by sending a WINDOW_UPDATE frame.)
=> Don't apply INITIAL_WINDOW_SIZE to connection window

httpcore5-testing/pom.xml, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/ReactiveEchoProcessor.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/ReactiveRandomProcessor.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/ReactiveTestUtils.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/reactive/ReactiveClientTest.java
This commit adds some utilities that make it easier to write tests of
reactive functionality, including an echo server, a random server, and a
random stream generator. The existing reactive tests have been
refactored to use the latter.
=> Add reactive test code

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/ReactiveTestUtils.java
This commit implements the following changes to input window management:
1. The `lowMark` is set according to local settings, not remote settings
2. The connection window is set to `Integer.MAX_VALUE` during `SETTINGS` exchange
3. The connection window low mark is now a constant value (10 MiB)
4. The input window update code in `onOutput` has been removed
=> Clean up connection window management

httpcore5/src/main/java/org/apache/hc/core5/ssl/SSLContextBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/ssl/SSLContexts.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/TestSSLContextBuilder.java
TLSv1.0 and TLSv1.1 are deprecated from the year 2020 onwards. It would be better for the SSLContextBuilder to use a newer (not deprecated) encryption protocol by default if the user does not provide any.
This change will not prevent the user to still use an older version when providing the old one.
=> Switched to TLSv1.2 as default protocol if none provided

httpcore5/src/main/java/org/apache/hc/core5/util/CharArrayBuffer.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestCharArrayBuffer.java
**CharArrayBuffer** implemented the **CharSequence** interface, 
and **CharSequence** define method:   
`public CharSequence subSequence(final int beginIndex, final int endIndex)`
Threre are two problem in original implementation of `CharArrayBuffer.subSequence`
1. It call `CharBuffer.wrap(buffer.array, beginIndex, endIndex)` directly，but the 3rd parameter of the `CharBuffer.wrap` method is length, it means how many chars need to copy, not endIndex. It makes some problem such as pass CharArrayBuffer as a CharSequence in to Regex's matcher method like following:   
```CharArrayBuffer charSequence = new CharArrayBuffer(8);   
charSequence.append("aabb123c");   
Pattern p = Pattern.compile("\\D*(\\d+)\\D*");   
Matcher m = p.matcher(charSequence);   
Assert.assertEquals("123", …
```
=> Fix CharArrayBuffer.subSequence(beganIndex,endIndex) to return right result.

httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/H2GreetingServer.java, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/examples/ReactiveFullDuplexClientExample.java, httpcore5-testing/src/main/java/org/apache/hc/core5/benchmark/HttpBenchmark.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/classic/LoggingBHttpClientConnection.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/classic/LoggingBHttpServerConnection.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/classic/LoggingHttp1StreamListener.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/classic/Wire.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/LogAppendable.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/LoggingH2StreamListener.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/LoggingHttp1StreamListener.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/LoggingIOSession.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/LoggingIOSessionListener.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/compatibility/http2/H2CompatibilityTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ServerHttp1StreamDuplexer.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ServerHttp1StreamHandler.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicReverseProxyExample.java
Methodology:
I used the intellij idea ultimate edition inspection "non-constant
string concatenation as argument to logging call" to find and
auto-fix occurrences of this pattern.
Followed up with intellij idea fixes for "Unnecessary call to 'toString'"
=> HTTPCORE-636: Logging statements use slf4j interpolation over concatenation

httpcore/src/main/java/org/apache/http/pool/AbstractConnPool.java
pool cached in getPoolEntryBlocking could be removed from routeToPool map by another thread while the thread executing getPoolEntryBlocking was waiting on condition.
After this change we check routeToPool after every wait.
=> HTTPCORE-634: fix possible race condition

httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/classic/SharedOutputBuffer.java, httpcore5/src/test/java/org/apache/hc/core5/http/nio/support/classic/TestSharedOutputBuffer.java
It is possible for `flush` to be called after `markCompleted` and both would call `dataStreamChannel.endStream` which is incorrect, `endStream` must only be called once.
=> HTTPCORE-638: SharedOutputBuffer must only call dataStreamChannel.endStream() once

httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/BHttpConnectionBase.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/IncomingHttpEntity.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/BasicHttpEntity.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EmptyInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/NullEntity.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestBasicHttpEntity.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestInputStreamEntity.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestNullEntity.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestStandardInterceptors.java
NullEntity can be used in place of an empty ByteArrayEntity with
no content-type.
=> HTTPCORE-643 Implement NullEntity for convenience

httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2ProtocolNegotiationTest.java
Tested across the 251 boundary on oracle and azul runtimes.
=> Fix testNegotiateProtocol test failures on recent java8 releases

httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/BHttpConnectionBase.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ChunkedOutputStream.java
This PR includes two commits, because this fix is implemented in two parts:
1. Reuse chunk buffers between requests using a persistent connection in order to eliminate the performance cost of allocating buffers
2. Increase the default value from 2 KiB to 8 KiB matching the default buffer size.
=> HTTPCORE-645: Increase blocking default chunk size to 8 KiB and reuse chunk buffers

httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSessionImpl.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncReverseProxyExample.java
As discussed some time ago on the dev mailing list.
=> Use decimal numbers for endpoint/execution IDs

httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/AbstractHttp1StreamDuplexer.java
I’ve observed a deadlock when writing to a ContentOutputStream obtained through AbstractClassicEntityProducer. We’ve looked through the layers at how ContentOutputStream’s SharedOutputBuffer coordinates between threads and traced this to a race condition in AbstractHttp1StreamDuplexer. The issue is that AbstractHttp1StreamDuplexer.requestSessionOutput can be called, but the event loop never calls onOutput, which then doesn’t call produceOutput.
When a thread calls requestSessionOutput in the duplexer, it increments an AtomicInteger called outputRequests (used to track the current number of requests for output), and sets an OP_WRITE event. An event thread notices the OP_WRITE state, and responds to it by calling AbstractHttp1StreamDuplexer.onOutput(). This method then calls …
=> Prevent an output request in AbstractHttp1StreamDuplexer from being erased when it occurs simultaneously with a call to onOutput

httpcore5/src/main/java/org/apache/hc/core5/util/VersionInfo.java, httpcore5/src/main/resources/org/apache/hc/core5/version.properties
Remove the non-reproducible timestamp as well as deprecate the field and getter for this property.
This will be backported to 5.0.x too if no one objects.
=> HTTPCORE-632: version.properties contains non-interpolated value

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/TestReactiveDataConsumer.java
This change addresses a race condition I’ve observed when executing HTTP calls using a `ReactiveEntityProducer` and a `ReactiveResponseConsumer`. If not all dependencies have been set on the future owned by `InternalAbstractHttpAsyncClient` by the time `ReactiveResponseConsumer.streamEnd` is called, calling `ComplexFuture.setDependency` will throw an `InterruptedIOException` because the future has already been successfully completed. Eventually, `ReactiveDataConsumer.failed` will be called. As long as `ReactiveDataConsumer.flushToSubscriber` was not called between setting `completed = true` in `streamEnd` and setting `exception = cause` in `failed`, the next invocation of `flushToSubscriber` will throw an exception to the subscriber because error messages are published first. I’ve …
=> Make ReactiveDataConsumer.failed a no-op if it has already been marked as complete

.travis.yml
More and more software development is being done on ARM64 CPU architecture.
It would be good if HttpComponents Core is being regularly tested on ARM64.
=> Build and test on both AMD64 and ARM64

.travis.yml, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/frame/StreamIdGenerator.java
Unfortunately https://github.com/apache/httpcomponents-core/pull/228 did not work.
`arm64-graviton2` is available only for travis-ci.com, while Apache uses travis-ci.org.
With this PR I'm changing it to use the old `arm64` instead of `arm64-graviton2`.
But there is a small problem - https://hub.docker.com/r/kennethreitz/httpbin/tags is amd64 only and HttpBinIT fails:
```
[ERROR] Errors: 
[ERROR]   HttpBinIT.executeHttpBin:51 » Execution java.net.ConnectException: Connection ...
```
So, the `arm64` job should be executed without `-P docker` profile.
I've also merged `jobs` and `matrix` elements - they are aliases.
=> Build on arm64 (second attempt)

httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EntityUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestEntityUtils.java
Currently, the EntityUtils.toString method ignores the maxRequestLength parameter.
=> Bug fix: Fixed ignoring maxResultLength in toString method of EntityUtils

httpcore-ab/src/test/java/org/apache/http/benchmark/HttpServer.java, httpcore-nio/src/main/java/org/apache/http/impl/nio/reactor/DefaultConnectingIOReactor.java, httpcore-nio/src/main/java/org/apache/http/nio/NHttpConnection.java, httpcore-nio/src/main/java/org/apache/http/nio/params/NIOReactorPNames.java, httpcore-nio/src/main/java/org/apache/http/nio/reactor/EventMask.java, httpcore-nio/src/main/java/org/apache/http/nio/reactor/IOEventDispatch.java, httpcore-nio/src/main/java/org/apache/http/nio/reactor/IOSession.java, httpcore-nio/src/test/java/org/apache/http/impl/nio/reactor/TestDefaultListeningIOReactor.java, httpcore/src/main/java-deprecated/org/apache/http/impl/SocketHttpClientConnection.java, httpcore/src/main/java-deprecated/org/apache/http/impl/SocketHttpServerConnection.java, httpcore/src/main/java-deprecated/org/apache/http/protocol/BasicHttpProcessor.java, httpcore/src/main/java-deprecated/org/apache/http/protocol/ExecutionContext.java, httpcore/src/main/java/org/apache/http/ExceptionLogger.java, httpcore/src/main/java/org/apache/http/HttpStatus.java, httpcore/src/main/java/org/apache/http/entity/ContentLengthStrategy.java, httpcore/src/main/java/org/apache/http/entity/ContentType.java, httpcore/src/main/java/org/apache/http/impl/BHttpConnectionBase.java, httpcore/src/main/java/org/apache/http/params/CoreConnectionPNames.java, httpcore/src/main/java/org/apache/http/params/CoreProtocolPNames.java, httpcore/src/main/java/org/apache/http/protocol/HttpContext.java, httpcore/src/main/java/org/apache/http/ssl/SSLContextBuilder.java, httpcore/src/test/java/org/apache/http/integration/TestSyncHttp.java, httpcore/src/test/java/org/apache/http/pool/TestConnPool.java, httpcore/src/test/java/org/apache/http/ssl/TestSSLContextBuilder.java
Each commit in this PR comprise one kind of cleanup/change:
- Make better use of Map APIs.
- Remove redundant modifiers.
- Use Collections.addAll() API instead of loops.
- Remove redundant returns.
- No need to explicitly declare an array when calling a vararg method.
- Remote extra semicolons (;).
=> 4.4.x use better map apis and more

httpcore/src/main/java/org/apache/http/HttpStatus.java, httpcore/src/main/java/org/apache/http/impl/EnglishReasonPhraseCatalog.java
Hi guys!
The 4.x version of the project doesn't provide `429 Too Many Requests` status by `org.apache.http.HttpStatus`.
This is a little PR to extend it. Because we prefer use HTTP Statuses via this library.
=> Add HttpStatus.SC_TOO_MANY_REQUESTS 429 Too Many Requests

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
This PR is adding `appendPath` and `appendPathSegments` methods to `URIBuilder`.
The added benefit of these methods is allowing a URI to be built successively throughout an application. As an example, one method could set the base URL, pass the `URIBuilder` along to the next method which can set an API version, and have a third method set the context path.
This functionality does not fit nicely in an external utility method, as it breaks the builder pattern/fluent style.
This would be equivalent to Spring's [UriComponentsBuilder # path](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html#path-java.lang.String-). When migrating a recent application from Spring to HTTP Components, an equivalent for this method was lacking.
=> Add appendPath and appendPathSegments methods to URIBuilder

httpcore5/src/main/java/org/apache/hc/core5/http/HttpEntity.java
See [HTTPCORE-656](https://issues.apache.org/jira/browse/HTTPCORE-656)
While writing this, I noticed that `HttpEntity` is also used by HTTP requests, therefore I added that this only applies to HTTP entities from HTTP responses.
Additionally the [tutorial](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fundamentals.html#d5e145) which mentions this behavior is part of the HTTP client project, therefore I decided against linking it from the documentation because that might be confusing.
=> HTTPCORE-656: Improve HttpEntity.getContent() documentation

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/H2ServerBootstrap.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/classic/ClassicServerBootstrapFilterTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/AsyncServerBootstrapFilterTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2ServerBootstrapFiltersTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/AsyncServerBootstrap.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/ServerBootstrap.java
When `addFilterLast` is called on a `ServerBootstrap`, `AsyncServerBootstrap` or `H2ServerBootstrap`, the given filter is added as last element of the filter chain. That may seem correct, but it causes them to be ignored. The reason is the `Terminal*Filter` that's initially the last element. In all three cases, this does not delegate to the chain. As a result, anything added with `addFilterLast` is currently completely ignored.
This change adds the filter as last in the chain of actual filters, just before the `Terminal*Filter` of which it could be said it's not an actual filter.
=> Add filters before MAIN_HANDLER so they won't be ignored

httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSessionImpl.java
I'm not including change on `setEventMask(final int newValue)` method as there is currently no lock and I have no knowledge on its usage. Tell me if you want this modification as well.
I'm not including a new test case because the race condition is quite hard to reproduce without some "artificial" help like making the code sleep in the `setEvent()` method.
=> HTTPCORE-659 Race condition in IOSessionImpl when setting event

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java, httpcore5/src/main/java/org/apache/hc/core5/http/HttpHost.java, httpcore5/src/main/java/org/apache/hc/core5/http/ProtocolVersion.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/BasicHeaderValueParser.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/HeaderGroup.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/MessageSupport.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/UriPatternMatcher.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/UriPatternOrderedMatcher.java, httpcore5/src/main/java/org/apache/hc/core5/ssl/SSLContextBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/util/Tokenizer.java, httpcore5/src/main/java/org/apache/hc/core5/util/VersionInfo.java
* Use Empty collections
* Unnecessary boxing
* Unnecessary toString
* Use Math.max
=> Minor Improvement:

httpcore5/src/main/java/org/apache/hc/core5/http/HttpStatus.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/EnglishReasonPhraseCatalog.java
The RFC 2817 describes following HTTP Status codes:
426 Update Required
=> HTTPCORE-661 - add http status code 426

httpcore5/src/main/java/org/apache/hc/core5/http/HttpStatus.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/EnglishReasonPhraseCatalog.java
The RFC 8470 describes following HTTP Status codes:
425 Too Early
Currently, the HTTP Status code list doesn't include this codes.
https://tools.ietf.org/html/rfc8470
=> [HTTPCORE-663] - add http status code 425

httpcore5/src/main/java/org/apache/hc/core5/util/TimeValue.java, httpcore5/src/main/java/org/apache/hc/core5/util/Timeout.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTimeValue.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTimeout.java
Java 8 delivers the `java.time` package including the `Duration` class which is a nice way to express timeouts, just like our `TimeValue` and `Timeout` classes. Therefore, this PRs allows conversions between our types and a Java Duration for use cases where an application already deals with Durations.
This PR also updates the tests affected to no longer use the deprecated `Assert.assertThat`.
=> Let TimeValue/Timeout convert to and from Duration.

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
Add `URIBuilder#getFirstQueryParam(String)` to query a parameter by name.
=> Add URIBuilder#getFirstQueryParam(String) to query a parameter by name.

RELEASE_NOTES.txt, httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/nio/entity/TestDigestingEntityConsumer.java, httpcore5/src/test/java/org/apache/hc/core5/http/nio/entity/TestDigestingEntityProducer.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestTextUtils.java
The check `b < 16` was faulty and would have added a '0' for negative values.
E.g. for `(byte) 0xFF` the result would have been `"0ff"`.
=> Fix TextUtils.toHexString having incorrect result for negative values

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
https://issues.apache.org/jira/browse/HTTPCLIENT-1916 .
Note that I have marked the new method as "since 5.2".
=> HTTPCLIENT-1916: Add URIBuilder.removeParameter

httpcore5/src/main/java/org/apache/hc/core5/net/Host.java, httpcore5/src/main/java/org/apache/hc/core5/net/URISupport.java, httpcore5/src/test/java/org/apache/hc/core5/http/TestHttpHost.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestHost.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIAuthority.java
This adds support for bracketed IPv6 host parsing to the following:
* `org.apache.hc.core5.net.Host.create(String)`
* `org.apache.hc.core5.net.URIAuthority.create(String)`
* `org.apache.hc.core5.http.HttpHost.create(String)`
This commit does not address "InetAddressUtils: Parsing may fail when an
IPv6 scope id might be provided." which does not appear to be relevant to
URI encoding, I need to find the original discussion to better understand
this piece.
=> HTTPCORE-616: Make parsing IPv6 ready

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java
From RFC7540 §6.9.2:
> The connection flow-control window can only be changed using
> WINDOW_UPDATE frames.
=> Don't change conn flow control window based on remote SETTINGS

.travis.yml, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/ssl/ConscryptSupport.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/ssl/H2TlsSupport.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2AlpnTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2ProtocolNegotiationTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2ServerAndMultiplexingRequesterTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2ServerAndRequesterTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/JSSEProviderIntegrationTest.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/ssl/SSLIOSession.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/TestSSLContextBuilder.java, pom.xml
Folks
I would like to replace reflective calls to ALPN related methods with new API introduced in Java 8u251. This will fix incompatibility with Java 16 onward without a full upgrade to Java 11. The downside is that the project can no longer be built with Oracle Java 8 and will hence on require a fairly recent OpenJDK. 
The 5.2 code builds correctly with Apache Jenkins but no longer builds with Travis CI Java 8 JDKs.
https://ci-builds.apache.org/job/HttpComponents/job/HttpComponents%20Core%205.2.x%20Java8u251/2/
https://github.com/apache/httpcomponents-core/runs/2679553610
@garydgregory @rschmitt Please let me know if it is OK with you.
=> Use jep244 (ALPN support) was back-ported to java 8u251

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java
What?
Adding an overloaded method to uri builder to add NameValuePair as query param.
Why?
At times some of the query params are constant and do not change in terms of key and value.
In those cases it is better to make NameValuePair instances as static and re-using them instead of
creating an instance everytime.
=> Adds utility method to add name value pair for uri builder

httpcore5/src/main/java/org/apache/hc/core5/ssl/SSLContextBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/DummyProvider.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/TestSSLContextBuilder.java
This change ads support for specifying JCA provider for loading trust manager/key managers.
Without this fix, the corresponding providers have to be loaded into the system which is not always desirable or possible.
I've refactored the `testBuildWithProvider..()` tests along the way, as they wouldn't have failed even if the `setProvider()` instruction was missing. The `DummyProvider` is quite wonky, but it does the job of verifying that the specified provider has been used.
=> HTTPCORE-682: Custom provider for key manager/trust manager initialization

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2RequestConverter.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2ResponseConverter.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/TestDefaultH2RequestConverter.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/TestDefaultH2ResponseConverter.java, httpcore5/src/main/java/org/apache/hc/core5/http/HttpHeaders.java
as rfc7540 section 8.1.2.2 defined.
=> HTTPCORE-692 add new rules for H2 header check

httpcore5/src/main/java/org/apache/hc/core5/http/ssl/TLS.java, httpcore5/src/test/java/org/apache/hc/core5/http/ssl/TLSTest.java
Creating the unit tests for the enum `TLS` I realized that was not possible to check if the method `TLS.excludeWeak` it worked as expected and excluded the disabled protocols, without having to manually check one by one.
Now it's possible to check if a given protocol its enabled.
=> Check if a given protocol is secure and  enabled.

httpcore5-reactive/pom.xml, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/TestReactiveDataConsumer.java, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/TestReactiveDataProducer.java, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/TestReactiveEntityProducer.java, httpcore5-reactive/src/test/java/org/apache/hc/core5/reactive/examples/ReactiveFullDuplexClientExample.java, httpcore5-testing/pom.xml, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/Reactive3TestUtils.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/reactive/ReactiveRandomProcessor.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/reactive/ReactiveClientTest.java, pom.xml
Since the `ReactiveTestUtils` API references symbols from RxJava2, I've
left it untouched for now so that japicmp doesn't yell at me.
=> Upgrade to RxJava3

httpcore5/src/main/java/org/apache/hc/core5/net/InetAddressUtils.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestInetAddressUtils.java
Check input colon count before performing IPv6 regex validation.
`org.apache.hc.core5.net.InetAddressUtils.isIPv6Address` is used when constructing the `host` header for requests, and currently allocates a regex matcher when checking if the provided address is an IPv6 address. This is generates excess garbage and CPU cycles, especially in environments with mostly IPv4 addresses. By checking the colon count first, we see a 50x improvement checking `InetAddressUtils.isIPv6Address` for an IPv4 address.
The specific call backtrace seen looks like:
```
void java.util.regex.Matcher.<init>(Pattern, CharSequence)
Matcher java.util.regex.Pattern.matcher(CharSequence)
boolean org.apache.hc.core5.net.InetAddressUtils.isIPv6HexCompressedAddress(String)
boolean …
```
=> HTTPCORE-713 - Optimize InetAddressUtils#isIPv6*Address checks 

httpcore5/src/test/java/org/apache/hc/core5/concurrent/TestComplexFuture.java
Hey 😊
I want to contribute the following test:
Test that `future.failed(new java.lang.Exception())` is false when `failed` is called with the parameter `exception = new java.lang.Exception()`.
This tests the methods [`BasicFuture.failed`](https://github.com/apache/httpcomponents-core/blob/ece5876b65fad1a5ea0bf7985abc1b9aba1e08ac/httpcore5/src/main/java/org/apache/hc/core5/concurrent/BasicFuture.java#L128) and [`ComplexFuture.failed`](https://github.com/apache/httpcomponents-core/blob/ece5876b65fad1a5ea0bf7985abc1b9aba1e08ac/httpcore5/src/main/java/org/apache/hc/core5/concurrent/ComplexFuture.java#L78).
This test is based on the test [`testCancelled`](https://github.com/apache/httpcomponents-core/blob/ece5876b65fad1a5ea0bf7985abc1b9aba1e08ac/httpcore5/src/test/java/org/apache/hc/core5/concu …
=> (test) Add test for BasicFuture.failed and ComplexFuture.failed

pom.xml
SLF4J v1.7.25 verson is from March 2017 and it would be nice to keep up with more recent versions, just to be save.
Bumping to latest log4j binding as well.
=> Bumping versions of slf4j and log4j.

httpcore5/src/main/java/org/apache/hc/core5/reactor/SocksProxyProtocolHandler.java
- Convert remainingResponseSize to local variable since its use is local
- Pull down common code from if/else if statements
=> Minor cleanup

httpcore-nio/src/main/java/org/apache/http/nio/reactor/ssl/SSLIOSession.java
Update the logic back to consider empty buffered input in appBufferStatus before closing the SSLIOSession. 
This was the condition considered before this commit https://github.com/apache/httpcomponents-core/commit/211c21f86f27c8cc786a621fef2e1fdf3dc6b126#diff-b31898263b1708b34dde2568e52e870fa623a6d4be99ce247a7f6dc61f03ed7fR395
=> Consider empty buffered input in appBufferStatus to close the SSLIOSession.

httpcore-nio/src/main/java/org/apache/http/nio/pool/AbstractNIOConnPool.java, httpcore/src/main/java/org/apache/http/pool/AbstractConnPool.java
since in outer if conditions we have `freeCapacity > 0` and `totalAvailable > freeCapacity - 1`, which indicates  `totalAvailable` will always be large than 0, thus `!this.available.isEmpty()` is always true.
=> remove unnecessary if statement

httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EntityUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestEntityUtils.java, pom.xml
This makes it possible to read more than 4096 bytes of a `HttpEntity` with `EntityUtils.toByteArray` when you provide a `maxResultLength`, even if the entity doesn't have a content-length set (for example chunked).
It now reads the stream in a simliar way as `toCharArrayBuffer`.
=> Make it possible to read chunked entities with maxResultLength

httpcore5/src/main/java/org/apache/hc/core5/net/InetAddressUtils.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestInetAddressUtils.java
This Pull Request addresses the issue of properly handling scoped IPv6 addresses in the InetAddressUtils class. The previous implementation had incorrect behavior when handling scoped IPv6 addresses. This fix updates the logic to properly check the format of the scope ID and to return false when the address is not a valid standard or compressed IPv6 address.
=> Fix the issue with invalid scoped IPv6 addresses in InetAddressUtils.

httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/H2GreetingServer.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/classic/ClassicIntegrationTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java, httpcore5/src/main/java/org/apache/hc/core5/http/config/CharCodingConfig.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EntityUtils.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/StringEntity.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/entity/AbstractCharAsyncEntityProducer.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/entity/AbstractCharDataConsumer.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/entity/BasicAsyncEntityProducer.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SocksProxyProtocolHandler.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestChunkCoding.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestContentLengthInputStream.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestSessionInOutBuffers.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestEntityUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestHttpEntityWrapper.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestInputStreamEntity.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/entity/TestStringEntity.java
Previously, text-based content was many times encoded with ISO-8859-1. This has gradually fallen out of use in the past 10 to 15 years. Use US-ASCII where a 7-bit encoding scheme is required for everything related to text encoding use UTF-8.
This is just a draft to move to UTF-8. May contain incorrect changes. Intended for 5.3+ only.
=> Use either US-ASCII or UTF-8 encoding for text where approriate

httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicPostExecutionExample.java
The official document POST example incorrectly calls the GET method. For beginners, it is necessary to revise.
=> The official document POST example incorrectly calls the GET method

httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ForwardedRequest.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TesForwardedRequest.java
This pull request adds support for the Forwarded header to improve debugging, statistics, and location-dependent content generation. The Forwarded header contains information added by reverse proxy servers (load balancers, CDNs, etc.) that would otherwise be altered or lost when proxy servers are involved in the request path. The header can be used to identify the original request's IP address, host, and protocol, which can be valuable information for debugging, tracking traffic, and generating location-specific content.
By adding support for the Forwarded header, we can ensure that the complete request information is captured and available for use in debugging, tracking, and content generation. This can lead to more accurate logs, improved site performance, and better user experiences. …
=> Add a "Forwarded" HttpRequestInterceptor to add the "Forwarded" HTTP header.

httpcore5/src/main/java/org/apache/hc/core5/net/Host.java, httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicPostExecutionExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/support/TestBasicMessageBuilders.java
Improve IDN support in URI parsing by converting non-ASCII characters to their ASCII-compatible form using the java.net.IDN class. This allows for better interoperability with systems that may not support Unicode characters in domain names. The change was made by adding a conditional statement that checks if the hostname contains non-ASCII characters, and if so, applies the IDN conversion.
=> Add support for Internationalized Domain Names (IDN)

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java, httpcore5/src/test/java/org/apache/hc/core5/http/TestContentType.java
[HTTPCORE-745] ContentType.create(String, NameValuePair...) should make a defensive copy of its input array
=> [HTTPCORE-745] ContentType.create(String, NameValuePair...) defensive copy

httpcore-nio/src/main/java/org/apache/http/nio/reactor/ssl/SSLIOSession.java
Java SSLEngine is returning NOT_HANDSHAKING in most connection closure scenarios due to this [commit](https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/8d1b63a4db2c6348a97b3cf45bd4d2caa7cad6b5). This PR tries incorporate this behaviour.
=> HTTPCORE-740: Introduce Read interest during connection close for graceful closure

httpcore5/src/main/java/org/apache/hc/core5/reactor/ssl/SSLIOSession.java, httpcore5/src/test/java/org/apache/hc/core5/reactor/ssl/SSLIOSessionTest.java
This commit adds a try-catch block to handle potential UnsupportedOperationExceptions when calling getApplicationProtocol on an SSLEngine instance. If such an exception is thrown, we now default to "http/1.1" as the application protocol.
This change is necessary to ensure compatibility with older applications that do not support Application-Layer Protocol Negotiation (ALPN). However, this is a temporary workaround and upgrading to an SSL/TLS provider that supports ALPN is strongly recommended for better performance and security.
=> HTTPCORE-749: Handle UnsupportedOperationException in getApplicationProtocol.

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/FrameOutputBuffer.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/nio/TestFrameInOutBuffers.java
H2 protocol handler always resizes the output frame buffer to the remove MAX_FRAME_SIZE instead of doing so only then the remote MAX_FRAME_SIZE is lesser than the current MAX_FRAME_SIZE (partially reverts HTTPCORE-707)
=> HTTPCORE-751: H2 protocol handler incorrect handling of the remote MAX_FRAME_SIZE

BUILDING.txt
This PR updates the `BUILDING.txt` file to provide users with clear instructions regarding the minimum requirements for stable test execution.
The discussion is here: https://issues.apache.org/jira/browse/HTTPCORE-747
=> [HTTPCORE-747]: add information about the minimum requirement for stable test execution 

httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataConsumer.java, httpcore5-reactive/src/main/java/org/apache/hc/core5/reactive/ReactiveDataProducer.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/SocksProxy.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/Http1IntegrationTest.java, httpcore5/src/main/java/org/apache/hc/core5/concurrent/BasicFuture.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/AbstractHttp1StreamDuplexer.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ServerHttp1StreamDuplexer.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/entity/AbstractBinAsyncEntityProducer.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/entity/AbstractCharAsyncEntityProducer.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/HttpDateGenerator.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/UriPatternMatcher.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/UriPatternOrderedMatcher.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/UriRegexMatcher.java, httpcore5/src/main/java/org/apache/hc/core5/pool/LaxConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/pool/StrictConnPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/AbstractIOSessionPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/AbstractSingleCoreIOReactor.java, httpcore5/src/test/java/org/apache/hc/core5/concurrent/TestBasicFuture.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncReverseProxyExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/nio/support/classic/TestSharedOutputBuffer.java, httpcore5/src/test/java/org/apache/hc/core5/ssl/DummyProvider.java
Title: Refactor Synchronized Blocks to Use ReentrantLock 
This commit replaces instances of 'synchronized' keyword with the explicit use of 'ReentrantLock' to provide more advanced synchronization mechanisms. 
Changes include:
- Replaced 'synchronized' methods with methods that use a 'ReentrantLock' for managing state.
- Modified methods to use the 'lock' and 'unlock' methods of 'ReentrantLock' to ensure safe execution of critical sections.
These changes provide more granular control over locks, fair locking behavior, and the ability to interrupt thread waiting for a lock or timeout if a lock cannot be obtained immediately.
=> HTTPCORE-746 - Refactor Synchronized Blocks to Use ReentrantLock.

httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/SessionOutputBufferImpl.java, httpcore5/src/main/java/org/apache/hc/core5/util/ByteArrayBuffer.java, httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/nio/TestSessionInOutBuffers.java
This change causes SessionOutputBufferImpl to filter out all characters that
cannot be correctly converted to ISO-8859-1 by simple downcasting to a
byte.
Fix is inspired from: https://github.com/apache/httpcomponents-core/pull/116
Above mentioned fix was applied to Sync clients only. This request make similar change to async client. Once approved, I will raise similar request for 4.x branch.
=> Filter characters before byte conversion

httpcore5/src/main/java/org/apache/hc/core5/http/message/BasicHttpRequest.java, httpcore5/src/main/java/org/apache/hc/core5/http/support/AbstractRequestBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/net/URIAuthority.java, httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/HttpRequestWrapperTest.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/TestBasicMessages.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIAuthority.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
Description:
This pull request addresses the recommendations set out in RFC 9110 regarding the deprecation of the userInfo subcomponent in "http" or "https" URIs.
Changes:
- Removed all references to `userInfo` within the `URIAuthority` class.
- Deprecated methods in both `URIAuthority` and `URIBuilder` that utilized `userInfo`.
- Added exception handling for potential security risks associated with `userinfo` in received URIs.
=> HTTPCORE-756 - Deprecation of userInfo in Compliance with RFC 9110

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/concurrent/TestBasicFuture.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
This PR brings our `URIBuilder` in line with the standards set by RFC 9110, specifically Section 4.2.2 regarding HTTPS URIs.
Changes:
- Implemented a check to ensure `https` and `http` URIs do not have an empty host identifier.
[RFC](https://www.rfc-editor.org/rfc/rfc9110#name-https-uri-scheme) mandates such URIs be rejected as invalid.
=> HTTPCORE-756  - Enforced the requirement that `https` and `http` URIs must not have an empty host identifier

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/protocol/H2RequestContent.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/protocol/TestH2Interceptors.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestContent.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestStandardInterceptors.java
This pull request introduces changes to ensure our HTTP handling aligns with the requirements set out in [RFC9110](https://www.rfc-editor.org/rfc/rfc9110). Specifically, we've added validation to ensure that [OPTIONS](https://www.rfc-editor.org/rfc/rfc9110#name-options) requests containing content also include a valid Content-Type header.
=> HTTPCORE-756 -  Implement RFC9110 Content-Type Validation for OPTIONS Requests

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2RequestConverter.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/TestDefaultH2RequestConverter.java
This PR introduces validations for the :path pseudo-header field in accordance with the HTTP/2 specifications:
1. Ensures the :path pseudo-header field correctly represents the path and query parts of the target URI. Adheres to the "path-absolute" production. Optionally allows for a '?' character followed by the "query" production (as per Sections 3.3 and 3.4 of [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)]).
2. Validates that requests in asterisk form have the value '*' for the :path pseudo-header field.
3. Enforces that the :path pseudo-header field is not left empty for "http" or "https" URIs.
4. Guarantees that "http" or "https" URIs without a path component include a '/' value for the :path pseudo-header field.
5.  Implements an exception for OPTIONS requests:
If the …
=> Add validation for :path pseudo-header in HTTP/2 requests  RFC7540

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/DefaultConnectionReuseStrategy.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/DefaultBHttpClientConnection.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/BasicHeaderElement.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/BasicHeaderValueParser.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/MessageSupport.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/TestBasicHeaderValueFormatter.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/TestBasicHeaderValueParser.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/TestMessageSupport.java
This patch corrects the name/value parsing code in `BasicHeaderValueParser` and adds a number of message element formatting and parsing methods to `MessageSupport`
=> HTTP message support improvements

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/H2Processors.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ServerH2StreamHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/HttpProcessors.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/ServerSupport.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/HttpService.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ServerHttp1StreamHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestConformance.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ResponseConformance.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ResponseConnControl.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ResponseContent.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ResponseDate.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestStandardInterceptors.java
* Moved outgoing response conformance checks to the correct place in the protocol pipeline
* Added incoming request conformance checks based on RFC 9110.
=> HTTPCORE-756: server-side request / response protocol conformance checks

httpcore5/src/main/java/org/apache/hc/core5/ssl/SSLContextBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/ssl/TrustStrategy.java
This tries to make the security aspects of `TrustStrategy` clearer and suggest that it might not be needed when self-signed certificates are used.
Relates to https://github.com/apache/httpcomponents-client/pull/490
Any feedback is appreciated!
=> Add security warning to TrustStrategy documentation

httpcore5/src/main/java/org/apache/hc/core5/http/impl/DefaultConnectionReuseStrategy.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/DefaultContentLengthStrategy.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/BasicLineParser.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/TestDefaultConnectionReuseStrategy.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/TestDefaultContentLengthStrategy.java, httpcore5/src/test/java/org/apache/hc/core5/http/message/TestBasicLineParser.java
* Stricter parsing of response status line. The status code must consist of 3 digits.
* `Transfer-Encoding` handling and message frame validity improvements
=> HTTPCORE-756: RFC 9112 conformance improvements

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
Due to description of `URIBuilder.getFirstQueryParam()` it must return `null` if named parameter not found. When query is empty `this.queryParams == null` so calling `queryParams.stream()...` results in exception. So `queryParams` replaced with `getQueryParams()` which returns empty array in such case.
=> fix: URIBuilder.getFirstQueryParam throws exception when query is emty

httpcore5/src/main/java/org/apache/hc/core5/http/HttpResponse.java, httpcore5/src/main/java/org/apache/hc/core5/http/HttpStatus.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/StatusLine.java
I was originally searching for a way to test that `HttpStatus` code was "successful".
I didn't want to create a utility in my code base which checks `200 <= code && code < 300`, because it's a too frequent pattern.
I found `org.apache.hc.core5.http.message.StatusLine.StatusClass#from` but I spent a couple of minutes for that.
It would be much easier if it was mentioned in the `HttpStatus` JavaDoc, because those two entities are closely interconnected.
=> Mention HttpStatus and StatusCode in JavaDoc in more places

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientH2StreamHandler.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientH2StreamMultiplexer.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientPushH2StreamHandler.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ServerH2StreamHandler.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ServerH2StreamMultiplexer.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ServerPushH2StreamHandler.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/H2FileServerExample.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/H2GreetingServer.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/H2IntegrationTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/HttpRequestExecutor.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/HttpService.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ClientHttp1StreamDuplexer.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ClientHttp1StreamHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ServerHttp1StreamDuplexer.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/nio/ServerHttp1StreamHandler.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/BasicHttpContext.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ForwardedRequest.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/HttpCoreContext.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestConformance.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ResponseConnControl.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncClientSNIExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/AsyncFileServerExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicClientSNIExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicFileServerExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicGetExecutionExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/examples/ClassicPostExecutionExample.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TesForwardedRequest.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestHttpExecutionContext.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestStandardInterceptors.java
Since the inception HttpComponents used objects maps to represent context and parameters that could also be linked into a hierarchy with a parent map acting as a source of default values when not present in the local map. The use of object maps to represent a bag of all sorts of things was also a very hip (and much abused) concept at that time. Think Servlet attributes. 
A hierarchy of object maps is a very flexible and powerful structure. But it also has it cost in terms of complexity and in terms of performance. While it looked like a good idea in the beginning of HC 4.x development cycle, later it turned out to be causing more harm than good as the project progressed, mainly being unnecessarily complex, lacking proper type safety and adding too much overhead on top of that. In the HC …
=> HttpCoreContext to use instance variables for standard attributes

httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/JSSEProviderIntegrationTest.java
Update JSSEProviderIntegrationTest to skip conscript when on ppc64le.
Tested on:
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /home/jgoodyear/Documents/x1/maven/apache-maven-3.9.6
Java version: 1.8.0_412, vendor: IBM Corporation, runtime: /home/jgoodyear/Documents/x1/java/jdk8u412-b08/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.14.0-447.el9.ppc64le", arch: "ppc64le", family: "unix"
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Maven home: /Users/jgoodyear/Documents/x1/maven/apache-maven-3.9.5
Java version: 1.8.0_312, vendor: Azul Systems, Inc., runtime: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "14.5", arch: …
=> [HTTPCORE-767] Update JSSEProviderIntegrationTest to skip conscript 

httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/io/MultiByteArrayInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ChunkedInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/ContentLengthInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/EmptyInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/IdentityInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/SessionInputBufferImpl.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/EofSensorInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/SessionInputBuffer.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/ByteBufferEntity.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/entity/EmptyInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/classic/ContentInputStream.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/classic/SharedInputBuffer.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TimeoutByteArrayInputStream.java
Implement the "len" part of contract for `java.io.InputStream.read(byte[], int, int)`
- If `len` is zero, then no bytes are read and 0 is returned.
- Be explicit like we are for other invariants.
- Mostly do not reply on fall-through behavior.
- Tested with HTTP client git master at (current HEAD) commit 4009567af704530aa0578e34fc63dd8baa945d34
- Apply the same change to `SessionInputBuffer` and its implementation
=> Implement the "len" part of contract for java.io.InputStream.read(byte[], int, int)

httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
This PR introduces a new `plusAsBlank` flag to the `URIBuilder` class, allowing users to dynamically configure whether the '+' character in query parameters should be interpreted as a space (' ') or remain as a plus ('+').
=> HTTPCORE-770: Add plusAsBlank parameter to URIBuilder for dynamic configuration

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/H2MultiplexingRequester.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/H2ViaHttp1ProxyExecutionExample.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/ClientSessionEndpoint.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/H2TestClient.java, httpcore5-testing/src/main/java/org/apache/hc/core5/testing/nio/Http1TestClient.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/TLSIntegrationTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/TLSUpgradeTest.java, httpcore5/src/main/java/org/apache/hc/core5/concurrent/CompletingFutureContribution.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/HttpAsyncRequester.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/AsyncClientEndpoint.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/AbstractIOSessionPool.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/ProtocolIOSession.java, httpcore5/src/test/java/org/apache/hc/core5/concurrent/TestComplexFuture.java
- Reduces boilerplate when the same pattern is used
=> Refactor to use a new class CompletingFutureContribution

httpcore5/src/main/java/org/apache/hc/core5/concurrent/FutureContribution.java
I do not think it makes sense to build a new FutureContribution with a null callback.
This does not happen in the current code base.
=> A FutureContribution should not allow a null BasicFuture

httpcore5/src/main/java/org/apache/hc/core5/http/impl/DefaultConnectionReuseStrategy.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/TestDefaultConnectionReuseStrategy.java
This pull request introduces a change to the ´DefaultConnectionReuseStrategy´ class, allowing for more flexible handling of HTTP 408 (Request Timeout) responses. A new boolean parameter, ´forceCloseOn408´, has been added to make the connection reuse behavior configurable.
=>  HTTPCORE-769- Add Configurable Behavior for Handling 408 Responses in DefaultConnectionReuseStrategy

httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java, httpcore5/src/test/java/org/apache/hc/core5/http/TestContentType.java
This PR is an attempt to mitigate the issues highlighted in [HTTPCLIENT-2159,](https://issues.apache.org/jira/browse/HTTPCLIENT-2159). The root problem stems from how we are incorrectly handling certain content types by attaching charset parameters when they shouldn't have one. This update adjusts the way the Content-Type header handles specific cases, ensuring compliance with relevant specifications.
=> HTTPCLIENT-2159: Invalid handling of charset content type parameter

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2RequestConverter.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/DefaultH2ResponseConverter.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/H2Processors.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/protocol/H2RequestConformance.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/protocol/H2ResponseConformance.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/TestDefaultH2RequestConverter.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/TestDefaultH2ResponseConverter.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/protocol/TestH2Interceptors.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/compatibility/http2/AbstractHttp2CompatIT.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/compatibility/http2/ApacheHttpDCompatIT.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/compatibility/http2/NginxCompatIT.java
Presently HTTP/2 specific header field validation logic is backed into message converters. It makes it impossible to customize or disable. Moreover, when a HTTP/2 promise requests when get rejected as invalid due to presence of illegal headers, it cannot be correctly mapped to a handler because there is request object to start with, and as a result the error does not get correctly propagated to the caller.
This change-set corrects the problem by moving header field validation logic from message converters to the protocol processing chain, where it belongs.
This also enables us to to allow the `host` header in H2 promise requests when connecting to Apache HTTPD.
=> Move HTTP/2 illegal message header check from message converters to protocol interceptors

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/hpack/HPackDecoder.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/hpack/HPackEncoder.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/hpack/InboundDynamicTable.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/hpack/OutboundDynamicTable.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/hpack/TestHPackCoding.java
https://datatracker.ietf.org/doc/html/rfc7541#section-6.3
I discovered while using this library that common web browsers (chrome, edge, firefox) encountered HTTP2 protocol/HPACK compression errors when communicating with servers from this library. This was eventually traced to the browser and server using different values for the dynamic table size. I determined this was because this library does not send dynamic table size updates, and instead assumed both sides would immediately use the receiver's maximum table size. After adding encoder support for the dynamic table size update header signal, communication between browser and server is now error-free.
=> Properly alert receivers when using non-default dynamic table sizes for HPACK

httpcore5-testing/src/test/java/org/apache/hc/core5/testing/classic/ClassicIntegrationTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/HttpProcessors.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestTE.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestRequestTE.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestStandardInterceptors.java
This PR introduces two interceptors, H2RequestTE and RequestTE, to ensure the correct validation of the TE header in both HTTP/2 and HTTP/1.1 requests:
- H2RequestTE: Ensures that the TE header in HTTP/2 requests only contains the trailers directive, as required by the protocol. Any other transfer coding present will result in a ProtocolException.
- RequestTE: Validates the TE header in HTTP/1.1 requests by:
Ensuring the chunked transfer coding is not explicitly listed, as it is implicitly supported.
Verifying that the Connection: TE header is present to prevent TE from being forwarded by intermediaries.
=> Add TE header validation for HTTP/2 and HTTP/1.1 requests

httpcore5/src/main/java/org/apache/hc/core5/http/protocol/HttpDateGenerator.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/ResponseDate.java, httpcore5/src/test/java/org/apache/hc/core5/http/protocol/TestStandardInterceptors.java
This pull request optimizes the handling of the Date header in HTTP responses by ensuring that invalid Date headers are correctly replaced with the current time when necessary, following the guidelines in [RFC 9110, Section 6.6.1](https://www.rfc-editor.org/rfc/rfc9110.html#section-6.6.1). This behavior is optional and controlled by the replaceInvalidDate flag; by default, the behavior remains unchanged, preserving the previous logic.
=> Implement handling of invalid Date header in responses

httpcore5/src/main/java/org/apache/hc/core5/annotation/Experimental.java, httpcore5/src/main/java/org/apache/hc/core5/http/Method.java, httpcore5/src/main/java/org/apache/hc/core5/http/io/support/ClassicRequestBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/http/message/MessageSupport.java, httpcore5/src/main/java/org/apache/hc/core5/http/nio/support/AsyncRequestBuilder.java, httpcore5/src/main/java/org/apache/hc/core5/http/protocol/RequestContent.java, httpcore5/src/main/java/org/apache/hc/core5/http/support/BasicRequestBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/http/io/support/ClassicRequestBuilderTest.java
This PR introduces support for the HTTP Method `QUERY`, a safe-idempotent method that has a body. Since Node added [support for the query method](https://github.com/nodejs/node/issues/51562), there is now a need for clients to support it and behave properly (like sending content length == 0 when skipping a body).
=> Add HTTP Method QUERY support

httpcore5/src/main/java/org/apache/hc/core5/http/HttpResponseInterceptor.java
This PR polishes Javadoc for the `HttpResponseInterceptor` a bit.
=> Polish Javadoc for HttpResponseInterceptor

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/nio/TestAbstractH2StreamMultiplexer.java
This pull request fixes [HTTPCORE-772](https://issues.apache.org/jira/browse/HTTPCORE-772)
=> Update the pointer of Continuation's headerBuffer after copying the payload

httpcore5/src/main/java/org/apache/hc/core5/http/config/Http1Config.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/io/HttpRequestExecutor.java, httpcore5/src/test/java/org/apache/hc/core5/http/impl/io/TestHttpRequestExecutor.java
- Introduced a configuration option useRstOnTimeout in Http1Config to allow connections to be closed with an RST (Reset) signal when a timeout occurs.
- Updated HttpRequestExecutor to respect this configuration and invoke the appropriate close mode (CloseMode.IMMEDIATE for RST or Closer.closeQuietly for FIN).
- Maintained backward compatibility by defaulting to FIN-based connection closure.
This change improves flexibility and allows faster resource cleanup in timeout scenarios, aligning with the HTTP/1.1 recommendations for abnormal connection termination.
There is an issue where the connection close operation takes as long as the SocketTimeout value set in the SocketConfig after a Socket timeout occurs. This behavior arises because the NioSocketImpl performs an additional poll for the …
=> Optimize connection close logic to resolve timeout delay issue

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java
@arturobernalg Please review if you happen to have capacilty
=> HTTPCORE-774: fixed a race condition caused by concurrent update of the connection input window to the max value

httpcore5/src/main/java/org/apache/hc/core5/util/Deadline.java, httpcore5/src/test/java/org/apache/hc/core5/util/TestDeadline.java
Fixes overflow handling in Deadline calculation to ensure proper behavior when adding large time values, returning Deadline.MAX_VALUE in case of overflow.
=> Handle overflow in Deadline calculation to ensure correct behavior for large time values.

httpcore5/src/main/java/org/apache/hc/core5/net/PercentCodec.java, httpcore5/src/main/java/org/apache/hc/core5/net/URIBuilder.java, httpcore5/src/test/java/org/apache/hc/core5/net/TestURIBuilder.java
This pull request addresses issue [HTTPCORE-778](https://issues.apache.org/jira/browse/HTTPCORE-778?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel), which noted that our encoding for fragment identifiers in selectors was not fully compliant with RFC 3986. The RFC defines a fragment as:
`fragment = *( pchar / "/" / "?" )`
with:
`pchar = unreserved / pct-encoded / sub-delims / ":" / "@"`
=>  RFC 3986 conformant URI encoding policy

httpcore5/src/main/java/org/apache/hc/core5/reactor/IOSessionImpl.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/SingleCoreIOReactor.java
The `Socket` API is considered tightly coupled to Internet Protocol, and `socketChannel.socket()` is effectively a kind of unchecked downcast which will throw an exception if called on a Unix domain `SocketChannel`. This change removes some trivial coupling to `Socket` in preparation for introducing support for JEP 380 Unix domain sockets.
=> Avoid legacy Socket API in reactor code

RELEASE_NOTES.txt, httpcore5/src/main/java/org/apache/hc/core5/http/ContentType.java, httpcore5/src/test/java/org/apache/hc/core5/http/TestContentType.java
Add `ContentType.APPLICATION_ZIP_COMPRESSED`.
I ran into this one at work this week...
=> Add ContentType.APPLICATION_ZIP_COMPRESSED

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientH2StreamMultiplexerFactory.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ServerH2StreamMultiplexerFactory.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/H2MultiplexingRequesterBootstrap.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/H2RequesterBootstrap.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/bootstrap/H2ServerBootstrap.java
The FrameFactory interface is useful as, for example, it allows patching in PRIORITY support and changing frame values that are not generally configurable. It is set to the default impl in ClientH2StreamMultiplexerFactory making it hard to change. This PR adds the appropriate setter methods into ClientH2StreamMultiplexerFactory and H2RequesterBootstrap to choose a FrameFactory impl as so:
```java
H2RequesterBootstrap.bootstrap().setFrameFactory(impl).create()
```
=> h2: add choosing framefactory impl

httpcore5/src/main/java/org/apache/hc/core5/util/TextUtils.java
@arturobernalg Please double-check
=> Slightly better and efficient #toHexString method

httpcore5/src/main/java/org/apache/hc/core5/reactor/ssl/SSLIOSession.java
As a safety net for handling an infinite loop happening inside decrypt method (that has been reported here https://issues.apache.org/jira/browse/HTTPCORE-782), we propose a unproductive loop detection mechanism being added to it.
The mechanism counts the number of times the loop circles without consuming any data from the encrypted buffer while the unwrapping method reports a successful operation by returning OK status.
If we reach to 1000 unproductive loop, we throw an exception to escape the unproductive loop.
We are trying to have this feature inside production system, but have not seen the issue in weeks.
=> Safety net for infinite unproductive loop

httpcore5-testing/src/test/java/org/apache/hc/core5/testing/classic/ClassicTLSIntegrationTest.java, httpcore5-testing/src/test/java/org/apache/hc/core5/testing/nio/TLSIntegrationTest.java
I noticed after a macOS upgrade that these tests were failing, evidently due to some sort of firewall behavior. Looking at the problem, it seems like these tests actually intend to call `getLoopbackAddress`, rather than `getLocalHost`, which returns the IP address and hostname of the local host _on the network_, rather than on the loopback.
=> Fix hostname verification tests

httpcore5/src/main/java/org/apache/hc/core5/http/io/SocketConfig.java, httpcore5/src/main/java/org/apache/hc/core5/reactor/IOReactorConfig.java
This setting prevents connections from going idle for longer than five seconds. Overriding the operating system defaults seems to be a best practice:
https://docs.aws.amazon.com/lambda/latest/dg/best-practices.html
https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-reusing-connections.html
This prevents a failure mode where the network silently drops the connection, resulting in a stale connection in the connection pool that the client has no way of _knowing_ is stale:
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout
Connections that are dropped in this way create a significant risk of a subsequent request failure, and the exception thrown in this case may or may not be safely retriable. Since TCP …
=> Enable five-second TCP keep-alive by default

httpcore5/src/main/java/org/apache/hc/core5/http/HttpConnection.java
=> Fix JavaDoc for HttpConnection.close() to reference correct close(CloseMode) method

httpcore5-h2/src/main/java/org/apache/hc/core5/http2/frame/FrameFactory.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/frame/FrameType.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/AbstractH2StreamMultiplexer.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/impl/nio/ClientH2StreamMultiplexer.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/priority/PriorityFormatter.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/priority/PriorityMerge.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/priority/PriorityParams.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/priority/PriorityParamsParser.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/priority/PriorityParser.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/priority/PriorityValue.java, httpcore5-h2/src/main/java/org/apache/hc/core5/http2/protocol/H2RequestPriority.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/examples/ClassicH2PriorityExample.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/impl/nio/TestAbstractH2StreamMultiplexer.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/priority/TestPriorityMerge.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/priority/TestPriorityParamsParser.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/priority/TestPriorityParserAndFormatter.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/priority/TestPriorityValue.java, httpcore5-h2/src/test/java/org/apache/hc/core5/http2/protocol/H2RequestPriorityTest.java, httpcore5/src/main/java/org/apache/hc/core5/http/HttpHeaders.java
This PR adds core support for RFC 9218: we advertise SETTINGS_NO_RFC7540_PRIORITIES=1, gate PRIORITY_UPDATE emission on the peer’s setting (or pre-SETTINGS), parse/accept PRIORITY_UPDATE frames in the base muxer, and introduce  PriorityParamsParser for the Priority header (u/i members, tolerant parsing).
=> HTTP/2: implement RFC 9218 Extensible Prioritization Scheme for HTTP.

httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/AsyncServerBootstrap.java, httpcore5/src/main/java/org/apache/hc/core5/http/impl/bootstrap/ServerBootstrap.java
I migrated a project from httpcore4 to httpcore5 just recently and when it didn't work, I had to dive into the httpcore5 sources to understand what was going wrong and that I need to create a custom `RequestRouter` with `LOCAL_AUTHORITY_RESOLVER` scheme to get the same behavior as before with httpcore4 just using simple `ServerBootstrap` methods. It is quite a pain to build the custom `RequestRouter` in the application itself, especially because this isn't really very well documented.
With this new `setAuthorityResolver()` method, the legacy behavior can be achieved by calling `setAuthorityResolver(RequestRouter.LOCAL_AUTHORITY_RESOLVER)` in combination with `setCanonicalHostName("localhost")` on `ServerBootstrap` or `AsyncServerBootstrap` .
=> added setAuthorityResolver() methods to AsyncServerBootstrap / ServerBootstrap
